version: 2.1

orbs: # Reusable "modules" of config.
   aws-s3: circleci/aws-s3@2.0.0

workflows: # Define multiple workflows within a pipeline.
  verify_filesystem:
    jobs:
      - checkout
      - lint
      - log
          requires:
            - checkout

jobs:
  checkout:
    machine: true
    resource_class: sandboxi/runner # Deployed on a t2.xlarge instance (4vCPUs + 16GB RAM)
    parallelism: 4
    steps:
      - checkout
      - run: ls -al
      - run: 
          name: Create activation file
          command: sudo docker run gableroux/unity3d:2018.2.6f1 ./opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -createManualActivationFile || exit 0
      - persist_to_workspace: # Caching build dependencies for future runs.
          root: ~/demo-react-native
          paths:
            - android
      - run: ls -al
  lint:
    machine: true
    resource_class: sandboxi/runner # Deployed on a t2.xlarge instance (4vCPUs + 16GB RAM)
    steps:
      - run: pwd
      - run: ls -al
  log:
    machine: true
    resource_class: sandboxi/runner # Deployed on a t2.xlarge instance (4vCPUs + 16GB RAM)
    steps:
      - run: ls -al
      - attach_workspace:
          at: ~/demo-react-native
      - run: ls -al
      - aws-s3/sync:
          from: ~/demo-react-native/android
          to: 's3://olukotun-demo/android'
