version: 2.1

workflows:
  verify_filesystem:
    jobs:
      - checkout
      - lint
      - log:
          requires:
            - checkout

jobs:
  checkout:
    machine: true
    resource_class: sandboxi/runner
    steps:
      - checkout
      - run: pwd
      - run: ls -al
      - run: ls -al $CIRCLE_WORKING_DIRECTORY
      - run: 
          name: Create activation file
          command: sudo docker run gableroux/unity3d:2018.2.6f1 ./opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -createManualActivationFile || exit 0
      - persist_to_workspace:
          root: ./
          paths:
            - android
      - run: ls -al
  lint:
    machine: true
    resource_class: sandboxi/runner
    steps:
      - checkout
      - run: pwd
      - run: ls -al
  log:
    machine: true
    resource_class: sandboxi/runner
    steps:
      - run: pwd
      - run: ls -al
      - attach_workspace:
          at: ./
      - run: ls -al
